### ISSUE TITLE
Help me.

### ISSUE THREAD

**Issue by mishailovic** [cnlohr/pylotron#1]
How to run it on my esp8266. Readme too short and no instruction here. (Sorry for my bad English I'm from Russia)

**Comment by cnlohr** [comment]
You can look in the "esp" folder, then use the 0x00000.bin and 0x40000.bin firmwares.  You can flash these to an esp8266 using firmware flashing tools.  I can't really be more specific since those tools will depend on your OS.

**Comment by mishailovic** [comment]
(My os is Windows) I flash it, it's easy for me. I connect to AP ,open vnc viewer and.. what should I do next?

**Comment by cnlohr** [comment]
What do you see in your VLC when you connect it to 192.168.4.1?

can you run around with the keyboard keys?

**Comment by mishailovic** [comment]
Oh.. It working now! But new problem: the ground is red and  the sky is black.

**Comment by mishailovic** [comment]
I solve this problem, I just change the quality. Thank you very much! And goodbye. Your projects are very, very, very cool!

**Comment by cnlohr** [comment]
What VNC viewer did you end up using?

**Comment by mishailovic** [comment]
RealVNC Viewer

**Comment by cnlohr** [comment]
Thanks!
